name: dante
run-name: Running on ${{ github.repository }} by @${{ github.actor }}

env:
  MIRROR_URL: git@github.com:Jabolol/dante.git

on: [push, pull_request]

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    if: github.repository == 'EpitechPromo2027/B-CPE-200-BAR-2-1-dante-javier.rios-urbano'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0x7fffffff
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
